# Generated by Django 5.1.7 on 2025-03-22 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('pulse_to_meter_factor', models.FloatField()),
                ('optimal_production_per_min', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PulseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_count', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.device')),
            ],
            options={
                'indexes': [models.Index(fields=['device'], name='devices_pul_device__e1863c_idx'), models.Index(fields=['timestamp'], name='devices_pul_timesta_cb8132_idx')],
            },
        ),
    ]
